package com.kts.taxify.model;

public enum NotificationType {
    ADDED_TO_THE_RIDE,
    RIDE_ACCEPTED,
    VEHICLE_ARRIVED,
    RIDE_STARTED,
    SCHEDULED_RIDE,
    RIDE_FINISHED,
    CUSTOMER_SUPPORT_REQUIRED,
    USER_STATUS_CHANGE,
	RIDE_FINISHED_PASSENGER,
	RIDE_ASSIGNED,
	RIDE_FINISHED_DRIVER,
	RIDE_REJECTED,

	ON_DESTINATION_PASSENGER,

	ON_DESTINATION_DRIVER
}
